### ISSUE TITLE
TypeError: from_buffer() cannot return the address of the raw string within a bytes or unicode or bytearray object

### ISSUE THREAD

**Issue by eggplants** [eggplants/wbsv-cli#21]
起動時エラー
Requestsに問題あるような(全学計算機上で動かした時)
```bash:err
Traceback (most recent call last):
  File "/home/s1811528/usr/pip/bin/wbsv", line 7, in <module>
    from wbsv.main import main
  File "/home/s1811528/usr/pip/lib/python3.5/site-packages/wbsv/main.py", line 1, in <module>
    from . import Archive
  File "/home/s1811528/usr/pip/lib/python3.5/site-packages/wbsv/Archive.py", line 6, in <module>
    from requests.exceptions import TooManyRedirects
  File "/opt/nfs/anaconda3/lib/python3.6/site-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/opt/nfs/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/opt/nfs/anaconda3/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/opt/nfs/anaconda3/lib/python3.6/site-packages/OpenSSL/crypto.py", line 15, in <module>
    from OpenSSL._util import (
  File "/opt/nfs/anaconda3/lib/python3.6/site-packages/OpenSSL/_util.py", line 152, in <module>
    with ffi.from_buffer(b""):
TypeError: from_buffer() cannot return the address of the raw string within a bytes or unicode or bytearray object
```
関係モジュールの環境
```bash:module_check
$ pip list |grep -P '(?:requests|urllib|SSL)' 2>/dev/null
pyOpenSSL (19.1.0)  # Latest
requests (2.22.0)        #Old(Now: 2.23.0)
urllib3 (1.25.8)            # Latest
```

怪しそうな質問
https://stackoverflow.com/questions/60308164/pyopenssl-with-ffi-from-bufferb-error
https://github.com/paramiko/paramiko/issues/1027

**Comment by eggplants** [comment]
pipの各モジュールが古かったのでシステム更新後に上手く行くようになった

**Comment by eggplants** [comment]
またダメになった
```bash
$ wbsv
Traceback (most recent call last):
File "/home/xxxxxxxx/usr/pip/bin/wbsv", line 7, in <module>
 from wbsv.main import main
File "/home/xxxxxxxx/usr/pip/lib/python3.5/site-packages/wbsv/main.py", line 1, in <module>
 from . import Archive
File "/home/xxxxxxxx/usr/pip/lib/python3.5/site-packages/wbsv/Archive.py", line 6, in <module>
 from requests.exceptions import TooManyRedirects
File "/opt/nfs/anaconda3/lib/python3.6/site-packages/requests/__init__.py", line 95, in <module>
 from urllib3.contrib import pyopenssl
File "/opt/nfs/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
 import OpenSSL.SSL
File "/opt/nfs/anaconda3/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
 from OpenSSL import crypto, SSL
File "/opt/nfs/anaconda3/lib/python3.6/site-packages/OpenSSL/crypto.py", line 15, in <module>
 from OpenSSL._util import (
File "/opt/nfs/anaconda3/lib/python3.6/site-packages/OpenSSL/_util.py", line 152, in <module>
 with ffi.from_buffer(b""):
 TypeError: from_buffer() cannot return the address of the raw string within a bytes or unicode or bytearray object
```

**Comment by eggplants** [comment]
user環境にインストールをするとそちらの方を読むようになってエラーも消えた　解決

```bash
python3 -m pip install pyopenssl --user
```
